title: "Kane Weng"
description: "Robotics & CS @ University of Michigan"
url: "https://kane-weng.github.io" 
baseurl: "/my-site"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

# Site Author (Points to _data/authors.yml)
author: kane

plugins:
  - jekyll-include-cache

defaults:
  # standalone pages
  - scope:
      path: ""
      type: pages           
    values:
      layout: single
      author_profile: true
  # projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs" # Sidebar menu of all projects

# Project collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Header Navigation
header:
  nav: "main"

# Plugins
footer_scripts:
  - /assets/js/dark-mode.js

markdown: kramdown
kramdown:
  math_engine: mathjax

# Minimal Mistakes specific setting
mathjax: true

logo: "/assets/images/logo.png"